### ISSUE TITLE
GAE: Google Appengine: Error 500 at first start

### ISSUE THREAD

**Issue by Abdelkrim** [Abdelkrim/f5-waf-policy-editor#1]
Dear @aamaltf1,

**DESCRIPTION** :  [https://waffler.dev](https://waffler.dev) DOES NOT work at first start 

**ERROR** : 500 Server Errror

-------------

![waffler dev-error-500-Screenshot 2023-02-13 113820](https://user-images.githubusercontent.com/791663/218440550-66901bbc-270c-458c-9cae-269bb0b6bf83.jpg)
-------------

**How to resolve?**  the application runs after a reload of the page

**ACTION:** Could you please investigate the issue inside the monitoring ? 

-------------
![waffler dev-working-Screenshot 2023-02-13 120042](https://user-images.githubusercontent.com/791663/218440859-5d2f52ea-a78a-4d1e-a4a7-158f90864d04.jpg)
-------------

Thank you in advance,

**Comment by aamaltf1** [comment]
@Abdelkrim could not reproduce the bug.
https://waffler.dev/  work at first start

could try again.
